<?php

function dna_module_menu() {
    $items['dna_code'] = array(
        'title' => 'See your DNA code:',
        'page callback'=> 'drupal_get_form',
        'page arguments' => array('dna_module_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

    $items['dna_module_result'] = array(
        'title'=> 'Here is your code',
        'page callback' => 'dna_module_result',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}


function dna_module_form() {
    //Container wrapping the form///
    $form['dna_module_container'] = array(
        '#title' => 'DNA',
        '#type' => 'fieldset',
    );
    $form['dna_module_container']['input_code'] = array(
        '#title' => 'Input Code',
        '#type' => 'textfield',
        '#description' => t("Input half of your DNA code.  You can only enter uppercase A, T, C or G.  The DNA generator will complete your DNA double helix"),
        '#element_validate' => array('element_validate_input_code'),
        '#required' => TRUE,
    );

    $form['dna_module_container']['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Go!'
    );

    return $form;
}

function element_validate_input_code($element) {
    $code_input = ($element['#value']);
    if (preg_match('/^[ACTG ]*$/', $code_input) == false) {
        form_error($element, T('Please only use uppercase A, T, C or G!'));
    }
}



function dna_module_form_submit($form, &$form_state) {

    $complete_dna = "";

    $input_code = $form_state['values']['input_code'];

    $input_split = str_split($input_code);

    foreach($input_split as $dna) {
        if ($dna == 'A') {
            $complete_dna .= 'T';
        } elseif ($dna == 'T') {
            $complete_dna .= 'A';
        } elseif ($dna == 'C') {
            $complete_dna .= 'G';
        } elseif ($dna == 'G') {
            $complete_dna .= 'C';
        } else {
            $complete_dna .= $dna;
        }

        $_SESSION['dna_helix'] = $complete_dna;
        $form_state['redirect'] = 'dna_module_result';
    }
}

function dna_module_result() {
    $dna_helix = $_SESSION['dna_helix'];
    return $dna_helix;
}
